# Default values for nexus-chart.
# This is a YAML-formatted file.

nexusServiceName: nexus3
hostname: nexus3-kuewvp.apps.na46.prod.nextcle.com
imageName: quay.io/harsha544/nexus3:latest
memoryLimit: 2703Mi
